create table game_dimension(
	query_id int primary,
	responseid,
	responsename,
	queryname,
	releasedate,
	dlccount,
	metacritic,
	recomendationcount,
	controllersupport,
	isfree,
	platformwindows,
	platformlinux,
	platformmac,
	categorysinglePlayer,
	categorymultiplayer,
	categorycoop,
	categorymmo,
	categoryinapp_purchase,
	categoryincludesrc_sdk,
	categoryinclude_level_editor,
	CategoryVR_Support,
	GenreIsNonGame,
	GenreIsIndie,
	GenreIsAction,
	GenreIsAdventure,
	GenreIsCasual,
	GenreIsStrategy,
	GenreIsRPG,
	GenreIsSimulation,
	GenreIsEarlyAccess,
	GenreIsFreeToPlay,
	GenreIsSports,
	GenreIsRacing,
	GenreIsMassivelyMultiplayer,
	PriceFinal,
	SteamSpyOwners,
	AchievementCount,
	AchievementHighlightedCount,
	RequiredAge,
	PurchaseAvail,
	SubscriptionAvail,
	PriceInitial,
	PriceCurrency,
	SupportEmail,
	SupportURL,
	AboutText,
	ShortDescrip,
	DetailedDescrip,
	Reviews,
	PCMinReqsText,
	PCRecReqsText,
	LinuxMinReqsText,
	LinuxRecReqsText,
	MacMinReqsText,
	MacRecReqsText,
	PCReqsHaveMin,
	PCReqsHaveRec,
	LinuxReqsHaveMin,
	LinuxReqsHaveRec,
	MacReqsHaveMin,
	MacReqsHaveRec,
	ScreenshotCount,
	FreeVerAvail,
	SteamSpyOwnersVariance,
	SteamSpyPlayersEstimate,
	SteamSpyPlayersVariance
);

create table author_dimension(
	steam_id int  primary key,
	num_games_owned int not null,
	num_reviews int not null,
	playtime_forever float not null,
	playtime_last_two_weeks float not null,
	playtime_at_review float not null,
	last_time_played float not null,
	steam_purchase boolean not null,
	received_for_free boolean not null
);

create table review_fact(
	review_id int primary key,
	language text not null,
	review text not null,
	feel text not null,
	recommend boolean not null,
	votes_funny integer not null,
	votes_helpful integer not null,
	comment_count integer not  null,
	written_during_early_acces boolean not null,
	game_id int not null,
	author_id int not null,
	foreign key game_id references game_dimension(query_id)
	foreign key author_id references author_dimension(steam_id)
);

